version: '3.8'

services:
  web:
    build: .
    command: bash -c "uvicorn app.main:app --host 0.0.0.0 --port 8010"
    volumes:
      - .:/app
    ports:
      - "8010:8010"
    expose:
      - "8010"
    depends_on:
      - db
    environment:
      - DATABASE_URL=mysql+mysqlconnector://lentian:123456@db/shop
    networks:
      - app_network

  db:
    image: mysql:5.7
    restart: always
    volumes:
      - db_data:/var/lib/mysql
    environment:
      - MYSQL_DATABASE=shop
      - MYSQL_USER=lentian
      - MYSQL_PASSWORD=123456
    ports:
      - '3306:3306'
    expose:
      - '3306'
    networks:
      - app_network

volumes:
  db_data: {}

networks:
  app_network:
    driver: bridge