"""Added updated user model

Revision ID: 3cc2a5b6c37c
Revises: 51b330193319
Create Date: 2024-05-03 18:09:43.616807

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = '3cc2a5b6c37c'
down_revision: Union[str, None] = '51b330193319'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('password', sa.String(length=100), nullable=True))
    op.add_column('users', sa.Column('active', sa.Boolean(), nullable=True))
    op.drop_column('users', 'disabled')
    op.drop_column('users', 'hashed_password')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('hashed_password', mysql.VARCHAR(length=100), nullable=True))
    op.add_column('users', sa.Column('disabled', mysql.TINYINT(display_width=1), autoincrement=False, nullable=True))
    op.drop_column('users', 'active')
    op.drop_column('users', 'password')
    # ### end Alembic commands ###
